#!/usr/bin/env bash
set -e

# Count PRs you are requested to review.
count=$(gh search prs --review-requested=@me --state=open | wc -l)
if [ "$count" -eq 0 ]; then
    printf "There are \e[32m%d\e[0m PRs to review.\n" $count  # Green for 0
else
    printf "There are \e[31m%d\e[0m PRs to review.\n" $count  # Red for non-zero
fi
